### ISSUE TITLE
关于subconverter的PKG_BUILD_DEPENDS中libpcre2的疑问

### ISSUE THREAD

**Issue by nftbty** [tindy2013/openwrt-subconverter#1]
之前还是0.2.7版本的时候，试过用Lean的Lede编译过一次，当时`PKG_BUILD_DEPENDS`后的值带有+号，提示有未满足的依赖，要去掉+号，不知官方发布的ipkg是否用的同样的makefile编译成功的。不过今天看，更新到0.4.1，并且`PKG_BUILD_DEPENS`值前面的+号去掉了。不过还有一个疑问，提示“libpcre2不存在”。然后我看了下，不管是官方packages源的master、18.06、19.07三个分支，还是Lean的packages源，在libs里面，只有pcre2的PKG，libpcre2这个package是在pcre2这个PKG里定义的，也就是如果用OP官方或者Lean的Lede，需要将`PKG_BUILD_DEPENDS`中的`libpcre2`改为`pcre2`。不太清楚作者用的什么版本的op，是否直接有`libpcre2`这个PKG。
[https://github.com/openwrt/packages/blob/master/libs/pcre2/Makefile](url)
[https://github.com/coolsnowwolf/packages/blob/master/libs/pcre2/Makefile](url)

**Comment by nftbty** [comment]
另外，在更新0.4.1版以前，使用的是openssl，具体是repo自带的`PKG_NAME`为openssl1.1，版本1.1.1d。但是op也自带了openssl，只不过`PKG_NAME:=openssl`，版本同样是1.1.1d。想问下使用自己附带的openssl而不是op本身带的，是出于什么原因？如果使用op本身的，是否可以直接编译成功，还是需要加一些patch？
更新到0.4.1版以后，默认使用mbedtls编译，但如果自己修改为使用openssl应该也可以吧？

**Comment by tindy2013** [comment]
OpenSSL 和 mbedTLS 除了为 cURL 提供 SSL 支持以外仅用作 MD5 计算 所以不需要额外的 Patch 欢迎 PR 修正错误 （之前在本地编译通过了所以就没去管了:joy:

**Comment by nftbty** [comment]
@tindy2013 修改几种配置试了一下，首先需要去掉`CMAKE_OPTIONS`的`-DUSING_MALLOC_TRIM=ON`，因为看了下编译链里`malloc.h`没有`malloc_trim()`，然后搜了下整个op工程，发现带有`malloc_trim()`的`malloc.h`文件基本都是一些软件包自带的，比如“u-boot-2018.03”，我不清楚有没有办法在工具链里添加这个支持，所以先注释掉了。
  然后修改Makefile使用OpenSSL，mbedTLS，STD_REGEX，libpcre2都成功编译，其中STD_REGEX打上了我昨天提issue后你更新的那个补丁，不过等0.4.2发布以后就好了。所以我照着其他package，加了个config，用来配置编译使用的SSL和RegEx库，已提交PR #2 。这是第一次弄Pull Request，不知道有没有哪里出错。
