### ISSUE TITLE
更新版本信息到0.6.1后云编译，到 Compile firmware这一步就报错了。改回0.5.2编译就没问题，请问我是哪里出错了呢

### ISSUE THREAD

**Issue by aenstan** [tindy2013/openwrt-subconverter#5]
小白不太懂，麻烦大佬指正下，见笑了。
以下我是更新的Makefile：
include $(TOPDIR)/rules.mk

PKG_NAME:=subconverter
PKG_VERSION:=0.6.1
PKG_RELEASE:=1

PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL:=https://github.com/tindy2013/subconverter.git
PKG_SOURCE_SUBDIR:=$(PKG_NAME)-$(PKG_VERSION)
PKG_SOURCE_VERSION:=591f9ef6143a039a556547ddfe43355d99f03bd3
PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION)-$(PKG_SOURCE_VERSION).tar.gz
CMAKE_INSTALL:=1
PKG_BUILD_PARALLEL:=1

这是云编译里到 Compile firmware这一步报错的信息：
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
DUKTAPE_INCLUDE_DIRS (ADVANCED)
   used as include directory in directory /home/runner/work/AutoBuild-OpenWrt/AutoBuild-OpenWrt/openwrt/build_dir/target-x86_64_musl/subconverter-0.6.1
   used as include directory in directory /home/runner/work/AutoBuild-OpenWrt/AutoBuild-OpenWrt/openwrt/build_dir/target-x86_64_musl/subconverter-0.6.1
   used as include directory in directory /home/runner/work/AutoBuild-OpenWrt/AutoBuild-OpenWrt/openwrt/build_dir/target-x86_64_musl/subconverter-0.6.1
   used as include directory in directory /home/runner/work/AutoBuild-OpenWrt/AutoBuild-OpenWrt/openwrt/build_dir/target-x86_64_musl/subconverter-0.6.1
   used as include directory in directory /home/runner/work/AutoBuild-OpenWrt/AutoBuild-OpenWrt/openwrt/build_dir/target-x86_64_musl/subconverter-0.6.1
   used as include directory in directory /home/runner/work/AutoBuild-OpenWrt/AutoBuild-OpenWrt/openwrt/build_dir/target-x86_64_musl/subconverter-0.6.1
   used as include directory in directory /home/runner/work/AutoBuild-OpenWrt/AutoBuild-OpenWrt/openwrt/build_dir/target-x86_64_musl/subconverter-0.6.1
DUKTAPE_LIBRARY (ADVANCED)
    linked by target "subconverter" in directory /home/runner/work/AutoBuild-OpenWrt/AutoBuild-OpenWrt/openwrt/build_dir/target-x86_64_musl/subconverter-0.6.1
DUKTAPE_MODULE_LIBRARY (ADVANCED)
    linked by target "subconverter" in directory /home/runner/work/AutoBuild-OpenWrt/AutoBuild-OpenWrt/openwrt/build_dir/target-x86_64_musl/subconverter-0.6.1

CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "subconverter":

    "DUKTAPE_INCLUDE_DIRS-NOTFOUND"

CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "subconverter":

    "DUKTAPE_INCLUDE_DIRS-NOTFOUND"

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
make[3]: *** [/home/runner/work/AutoBuild-OpenWrt/AutoBuild-OpenWrt/openwrt/build_dir/target-x86_64_musl/subconverter-0.6.1/.configured_f1fe9e9e84a27da1892133ef63c0942a] Error 1
Makefile:78: recipe for target '/home/runner/work/AutoBuild-OpenWrt/AutoBuild-OpenWrt/openwrt/build_dir/target-x86_64_musl/subconverter-0.6.1/.configured_f1fe9e9e84a27da1892133ef63c0942a' failed
make[3]: Leaving directory '/home/runner/work/AutoBuild-OpenWrt/AutoBuild-OpenWrt/openwrt/package/openwrt-subconverter/subconverter'
time: package/openwrt-subconverter/subconverter/compile#0.17#0.05#0.23
package/Makefile:111: recipe for target 'package/openwrt-subconverter/subconverter/compile' failed
make[2]: Leaving directory '/home/runner/work/AutoBuild-OpenWrt/AutoBuild-OpenWrt/openwrt'
make[2]: *** [package/openwrt-subconverter/subconverter/compile] Error 2
package/Makefile:107: recipe for target '/home/runner/work/AutoBuild-OpenWrt/AutoBuild-OpenWrt/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: Leaving directory '/home/runner/work/AutoBuild-OpenWrt/AutoBuild-OpenWrt/openwrt'
make[1]: *** [/home/runner/work/AutoBuild-OpenWrt/AutoBuild-OpenWrt/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make: *** [world] Error 2
/home/runner/work/AutoBuild-OpenWrt/AutoBuild-OpenWrt/openwrt/include/toplevel.mk:222: recipe for target 'world' failed
##[error]Process completed with exit code 2.

**Comment by tindy2013** [comment]
自 v0.6.0 开始，subconverter 开始使用一个外部库 `duktape` 用于提供执行脚本所需的 JavaScript 运行环境。目前未添加该库的构建 Makefile 所以导致了编译时出错。

**Comment by aenstan** [comment]
明白了，谢谢解答
